# .github/workflows/build-dotnet.yml
name: Commit Update & Pull Requests

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.gitignore'
      - 'README.md'
      - '.github/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '.gitignore'
      - 'README.md'
      - '.github/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🔽 Checkout du code
        uses: actions/checkout@v3

      - name: 🧰 Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' # ou ta version

      - name: 📦 Restore les dépendances
        run: dotnet restore

      - name: 🏗 Build le projet
        run: dotnet build --no-restore --configuration Release

      - name: 🧪 Run les tests
        run: dotnet test --no-build --verbosity normal

      - name: 📦 Publish (framework-dependent)
        #run: dotnet publish -c Release --self-contained false -o ./publish
        run: dotnet publish ./BBR-Ban-Sync.csproj -c Release --self-contained false -o ./publish
      
      - name: 🔍 Liste des fichiers pour debug
        run: find ./publish
      
      - name: 📤 Upload de tout le contenu publish
        uses: actions/upload-artifact@v4
        with:
          name: BBR-Ban-Sync
          path: ./publish/**/*
