name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'
    paths-ignore:
      - '.gitignore'
      - 'README.md'
      - '.github/**'
  workflow_dispatch:
  
permissions:
  contents: write
  
jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    steps:
      - name: 🔽 Checkout du code
        uses: actions/checkout@v3

      - name: 🧰 Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: 🏷️ Extraire la version du tag
        id: version
        run: |
          TAG="${GITHUB_REF_NAME}"
          VERSION="${TAG#v}"
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          echo "Tag: $TAG / Version: $VERSION"

      - name: 📦 Restore les dépendances
        run: dotnet restore

      - name: 🏗 Build le projet
        run: dotnet build --no-restore --configuration Release -p:Version=${{ steps.version.outputs.version }} -p:AssemblyVersion=${{ steps.version.outputs.version }} -p:FileVersion=${{ steps.version.outputs.version }} -p:InformationalVersion=${{ steps.version.outputs.tag }}

      - name: 🚀 Publish EXE (self-contained)
        run: dotnet publish ./BBR-Ban-Sync.csproj -c Release -r win-x64 --self-contained true -o ./publish -p:Version=${{ steps.version.outputs.version }} -p:AssemblyVersion=${{ steps.version.outputs.version }} -p:FileVersion=${{ steps.version.outputs.version }} -p:InformationalVersion=${{ steps.version.outputs.tag }}

      - name: 📦 Créer l'archive ZIP
        run: |
          cd publish
          zip -r ../BBR-Ban-Sync.zip ./*

      - name: 📤 Upload de l'archive en tant qu'artifact
        uses: actions/upload-artifact@v4
        with:
          name: BBR-Ban-Sync-zip
          path: ./BBR-Ban-Sync.zip

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Télécharger l'archive ZIP depuis les artifacts
        uses: actions/download-artifact@v4
        with:
          name: BBR-Ban-Sync-zip
          path: ./

      - name: 📤 Créer la release GitHub avec l’archive
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: BBR-Ban-Sync.zip
        env:
          GITHUB_TOKEN: ${{ github.token }}
